# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a697565f1e84aaf71cc9a044c6629734f0302c5fc3b0b41d4286bbe819a277119aa5c0ae47c97032b3e5f7a676594b496bb9e7d3cd5915ecb51434bf1b73928

test:
  secret_key_base: 9059ac3f5ad35521df91e4c8bd44c6c06856efb95b60a8583c46b1c5bde5b36abedac12aaadbba0e2ea49f4db3fe1c5698b32923a3f863fa33de4947efe86e66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
